<?php
if (!defined('ABSPATH')) {
    exit;
}

class Animatrix_For_Elementor_Lists {

    public static function get_entrance_animations() {
        return [
            '' => __('None', 'elementor-advanced-animations'),
            'fade-in-up' => __('Fade In Up', 'elementor-advanced-animations'),
            'fade-in-down' => __('Fade In Down', 'elementor-advanced-animations'),
            'fade-in-left' => __('Fade In Left', 'elementor-advanced-animations'),
            'fade-in-right' => __('Fade In Right', 'elementor-advanced-animations'),
            'zoom-in' => __('Zoom In', 'elementor-advanced-animations'),
            'zoom-out' => __('Zoom Out', 'elementor-advanced-animations'),
            'bounce-in' => __('Bounce In', 'elementor-advanced-animations'),
            'slide-in-up' => __('Slide In Up', 'elementor-advanced-animations'),
            'slide-in-down' => __('Slide In Down', 'elementor-advanced-animations'),
            'slide-in-left' => __('Slide In Left', 'elementor-advanced-animations'),
            'slide-in-right' => __('Slide In Right', 'elementor-advanced-animations'),
            'flip-in-x' => __('Flip In X', 'elementor-advanced-animations'),
            'flip-in-y' => __('Flip In Y', 'elementor-advanced-animations'),
            'rotate-in' => __('Rotate In', 'elementor-advanced-animations'),
            'pulse-in' => __('Pulse In', 'elementor-advanced-animations'),
            'swing-in' => __('Swing In', 'elementor-advanced-animations'),
            'wobble-in' => __('Wobble In', 'elementor-advanced-animations'),
            'tada-in' => __('Tada In', 'elementor-advanced-animations'),
            'jack-in-box' => __('Jack In The Box', 'elementor-advanced-animations'),
            'roll-in' => __('Roll In', 'elementor-advanced-animations'),
            'light-speed-in' => __('Light Speed In', 'elementor-advanced-animations'),
            'flip' => __('Flip', 'elementor-advanced-animations'),
            'hinge' => __('Hinge', 'elementor-advanced-animations'),
            'bounce-in-down' => __('Bounce In Down', 'elementor-advanced-animations'),
            'bounce-in-left' => __('Bounce In Left', 'elementor-advanced-animations'),
            'bounce-in-right' => __('Bounce In Right', 'elementor-advanced-animations'),
            'bounce-in-up' => __('Bounce In Up', 'elementor-advanced-animations'),
            'fade-in-down-big' => __('Fade In Down Big', 'elementor-advanced-animations'),
            'fade-in-left-big' => __('Fade In Left Big', 'elementor-advanced-animations'),
            'fade-in-right-big' => __('Fade In Right Big', 'elementor-advanced-animations'),
            'fade-in-up-big' => __('Fade In Up Big', 'elementor-advanced-animations'),
            'flip-in-x' => __('Flip In X', 'elementor-advanced-animations'),
            'flip-in-y' => __('Flip In Y', 'elementor-advanced-animations'),
            'light-speed-in' => __('Light Speed In', 'elementor-advanced-animations'),
            'rotate-in-down-left' => __('Rotate In Down Left', 'elementor-advanced-animations'),
            'rotate-in-down-right' => __('Rotate In Down Right', 'elementor-advanced-animations'),
            'rotate-in-up-left' => __('Rotate In Up Left', 'elementor-advanced-animations'),
            'rotate-in-up-right' => __('Rotate In Up Right', 'elementor-advanced-animations'),
            'roll-in' => __('Roll In', 'elementor-advanced-animations'),
            'zoom-in-down' => __('Zoom In Down', 'elementor-advanced-animations'),
            'zoom-in-left' => __('Zoom In Left', 'elementor-advanced-animations'),
            'zoom-in-right' => __('Zoom In Right', 'elementor-advanced-animations'),
            'zoom-in-up' => __('Zoom In Up', 'elementor-advanced-animations'),
            'slide-in-down' => __('Slide In Down', 'elementor-advanced-animations'),
            'slide-in-left' => __('Slide In Left', 'elementor-advanced-animations'),
            'slide-in-right' => __('Slide In Right', 'elementor-advanced-animations'),
            'slide-in-up' => __('Slide In Up', 'elementor-advanced-animations'),
        ];
    }

    public static function get_scroll_animations() {
        return [
            '' => __('None', 'elementor-advanced-animations'),
            'parallax' => __('Parallax', 'elementor-advanced-animations'),
            'scale-on-scroll' => __('Scale On Scroll', 'elementor-advanced-animations'),
            'fade-on-scroll' => __('Fade On Scroll', 'elementor-advanced-animations'),
            'blur-on-scroll' => __('Blur On Scroll', 'elementor-advanced-animations'),
            'slide-on-scroll' => __('Slide On Scroll', 'elementor-advanced-animations'),
            'rotate-on-scroll' => __('Rotate On Scroll', 'elementor-advanced-animations'),
            'sticky-element' => __('Sticky Element', 'elementor-advanced-animations'),
            'typewriter' => __('Typewriter', 'elementor-advanced-animations'),
            'counter' => __('Counter', 'elementor-advanced-animations'),
            'progress-bar' => __('Progress Bar', 'elementor-advanced-animations'),
            'morph' => __('Morph', 'elementor-advanced-animations'),
            'tilt' => __('Tilt', 'elementor-advanced-animations'),
            'gradient-shift' => __('Gradient Shift', 'elementor-advanced-animations'),
            'neon-glow' => __('Neon Glow', 'elementor-advanced-animations'),
            'liquid' => __('Liquid Effect', 'elementor-advanced-animations'),
            'distortion' => __('Distortion', 'elementor-advanced-animations'),
            'glitch' => __('Glitch', 'elementor-advanced-animations'),
            'float' => __('Float', 'elementor-advanced-animations'),
            'wave' => __('Wave', 'elementor-advanced-animations'),
        ];
    }

    public static function get_hover_animations() {
        return [
            '' => __('None', 'elementor-advanced-animations'),
            'pulse' => __('Pulse', 'elementor-advanced-animations'),
            'bounce' => __('Bounce', 'elementor-advanced-animations'),
            'rubber-band' => __('Rubber Band', 'elementor-advanced-animations'),
            'shake' => __('Shake', 'elementor-advanced-animations'),
            'swing' => __('Swing', 'elementor-advanced-animations'),
            'tada' => __('Tada', 'elementor-advanced-animations'),
            'wobble' => __('Wobble', 'elementor-advanced-animations'),
            'jello' => __('Jello', 'elementor-advanced-animations'),
            'heart-beat' => __('Heart Beat', 'elementor-advanced-animations'),
            'flip-horizontal' => __('Flip Horizontal', 'elementor-advanced-animations'),
            'flip-vertical' => __('Flip Vertical', 'elementor-advanced-animations'),
            'glow' => __('Glow', 'elementor-advanced-animations'),
            'shadow-pulse' => __('Shadow Pulse', 'elementor-advanced-animations'),
            'border-fill' => __('Border Fill', 'elementor-advanced-animations'),
            'text-shadow' => __('Text Shadow', 'elementor-advanced-animations'),
            'gradient-shift' => __('Gradient Shift', 'elementor-advanced-animations'),
            'skew' => __('Skew', 'elementor-advanced-animations'),
            'grow' => __('Grow', 'elementor-advanced-animations'),
            'shrink' => __('Shrink', 'elementor-advanced-animations'),
            'float' => __('Float', 'elementor-advanced-animations'),
            'sink' => __('Sink', 'elementor-advanced-animations'),
            'buzz' => __('Buzz', 'elementor-advanced-animations'),
            'buzz-out' => __('Buzz Out', 'elementor-advanced-animations'),
            'forward' => __('Forward', 'elementor-advanced-animations'),
            'backward' => __('Backward', 'elementor-advanced-animations'),
        ];
    }
     public static function get_exit_animations() {
        return [
            '' => __('None', 'elementor-advanced-animations'),
            'fade-out' => __('Fade Out', 'elementor-advanced-animations'),
            'fade-out-up' => __('Fade Out Up', 'elementor-advanced-animations'),
            'fade-out-down' => __('Fade Out Down', 'elementor-advanced-animations'),
            'fade-out-left' => __('Fade Out Left', 'elementor-advanced-animations'),
            'fade-out-right' => __('Fade Out Right', 'elementor-advanced-animations'),
            'zoom-out' => __('Zoom Out', 'elementor-advanced-animations'),
            'zoom-out-up' => __('Zoom Out Up', 'elementor-advanced-animations'),
            'zoom-out-down' => __('Zoom Out Down', 'elementor-advanced-animations'),
            'zoom-out-left' => __('Zoom Out Left', 'elementor-advanced-animations'),
            'zoom-out-right' => __('Zoom Out Right', 'elementor-advanced-animations'),
            'slide-out-left' => __('Slide Out Left', 'elementor-advanced-animations'),
            'slide-out-right' => __('Slide Out Right', 'elementor-advanced-animations'),
            'slide-out-up' => __('Slide Out Up', 'elementor-advanced-animations'),
            'slide-out-down' => __('Slide Out Down', 'elementor-advanced-animations'),
            'bounce-out' => __('Bounce Out', 'elementor-advanced-animations'),
            'bounce-out-down' => __('Bounce Out Down', 'elementor-advanced-animations'),
            'bounce-out-left' => __('Bounce Out Left', 'elementor-advanced-animations'),
            'bounce-out-right' => __('Bounce Out Right', 'elementor-advanced-animations'),
            'bounce-out-up' => __('Bounce Out Up', 'elementor-advanced-animations'),
            'fade-out-down-big' => __('Fade Out Down Big', 'elementor-advanced-animations'),
            'fade-out-left-big' => __('Fade Out Left Big', 'elementor-advanced-animations'),
            'fade-out-right-big' => __('Fade Out Right Big', 'elementor-advanced-animations'),
            'fade-out-up-big' => __('Fade Out Up Big', 'elementor-advanced-animations'),
            'flip-out-x' => __('Flip Out X', 'elementor-advanced-animations'),
            'flip-out-y' => __('Flip Out Y', 'elementor-advanced-animations'),
            'light-speed-out' => __('Light Speed Out', 'elementor-advanced-animations'),
            'rotate-out-down-left' => __('Rotate Out Down Left', 'elementor-advanced-animations'),
            'rotate-out-down-right' => __('Rotate Out Down Right', 'elementor-advanced-animations'),
            'rotate-out-up-left' => __('Rotate Out Up Left', 'elementor-advanced-animations'),
            'rotate-out-up-right' => __('Rotate Out Up Right', 'elementor-advanced-animations'),
            'roll-out' => __('Roll Out', 'elementor-advanced-animations'),
            'zoom-out-down' => __('Zoom Out Down', 'elementor-advanced-animations'),
            'zoom-out-left' => __('Zoom Out Left', 'elementor-advanced-animations'),
            'zoom-out-right' => __('Zoom Out Right', 'elementor-advanced-animations'),
            'zoom-out-up' => __('Zoom Out Up', 'elementor-advanced-animations'),
            'slide-out-down' => __('Slide Out Down', 'elementor-advanced-animations'),
            'slide-out-left' => __('Slide Out Left', 'elementor-advanced-animations'),
            'slide-out-right' => __('Slide Out Right', 'elementor-advanced-animations'),
            'slide-out-up' => __('Slide Out Up', 'elementor-advanced-animations'),
        ];
    }
}
